[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ignore both the Mapbox token AND all Firebase API keys (they all start with AIza)
[secrets.scan]
  omit_values = ["pk.eyJ1IjoiZGlkZXNpZGVybzEyIiwiYSI6ImNtaWgwYXY1bDA4dXUzZnEzM28ya2k5enAifQ.Ad7ucDv06FqdI6btbbstEg", "AIza"]
  omit_paths = [".next/**", ".netlify/**"]